name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main   # Deploy on push to main branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use the latest version

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Use the latest version
      with:
        node-version: '20'  # Use Node.js 20

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
